name: Java CI with Docker
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests=true

    - name: Docker Login
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        IMAGE_NAME="eks-demo" 
        docker build -t $IMAGE_NAME .

    - name: Push Docker image to Docker Hub
      run: |
        IMAGE_NAME="eks-demo" 
        COMMIT_ID=$(git rev-parse --short HEAD)
        IMAGE_NAME_FOR_TAG="${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME" 
        docker tag $IMAGE_NAME $IMAGE_NAME_FOR_TAG:$COMMIT_ID
        docker push $IMAGE_NAME_FOR_TAG:$COMMIT_ID

    - name: Checkout deployment.yaml from another repository
      uses: actions/checkout@v2
      with:
        repository: prashant-hariharan/eks-argocd
        ref: main
        path: eks-argocd
        
    #- name: Print folder Structure
      #run: ls -R
     
        
    - name: Install yq
      run: |
        wget https://github.com/mikefarah/yq/releases/download/v4.13.3/yq_linux_amd64.tar.gz -O /tmp/yq.tar.gz
        tar xvf /tmp/yq.tar.gz -C /tmp
        sudo mv /tmp/yq_linux_amd64 /usr/local/bin/yq
        yq --version

    - name: Update Image name 
      run: |
        IMAGE_NAME="eks-demo" 
        COMMIT_ID=$(git rev-parse --short HEAD)
        IMAGE_NAME_FOR_TAG="${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME"
        DEPLOYMENT_FILE="./eks-argocd/dev/deployment.yaml"
        yq eval ".spec.template.spec.containers[0].image = \"$IMAGE_NAME_FOR_TAG:$COMMIT_ID\"" -i "$DEPLOYMENT_FILE"
        echo "Image name updated to $IMAGE_NAME_FOR_TAG:$COMMIT_ID in $DEPLOYMENT_FILE"
        cat "$DEPLOYMENT_FILE"


    - name: Commit and Push Changes
      run: |
        git config --local user.email "${{ secrets.EMAIL }}"
        git config --local user.name "prashant-hariharan"

        git config --global user.email "${{ secrets.EMAIL }}"
        git config --global user.name "prashant-hariharan"
        cd eks-argocd
        COMMIT_ID=$(git rev-parse --short HEAD)
        git add ./dev/deployment.yaml
        git commit -m "Update image version to $COMMIT_ID"
        git push https://github.com/prashant-hariharan/eks-argocd.git HEAD:main
    
